framework:
    messenger:
        transports:
            synchronously: 'sync://'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%/failed'

            synchro_piezometry: '%env(MESSENGER_TRANSPORT_DSN)%/synchro_piezometry'

        routing:
            'App\Messenger\Message\StartSynchro': synchronously
            'App\Messenger\Message\SynchroPiezometry': synchro_piezometry

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
