version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ecodata
      POSTGRES_USER: app_ecodata
      POSTGRES_PASSWORD: "!PasswordEcoData!"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
        - "15672:15672"
        - "5672:5672"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
