parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $piezometryFrHubeau: '@piezometry.fr.hubeau'
            $europeanFireEFFIS: '@european_fire.effis'

    _instanceof:
        App\Doctrine\Listener\EntityListenerInterface:
            tags:
                - { name: doctrine.orm.entity_listener }

        App\Messenger\Dispatcher\SynchroDispatcherInterface:
            tags:
                - { name: app.messenger.dispatcher.synchro }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Doctrine/Entity/'
            - '../src/Doctrine/Listener/EntityListenerInterface.php'
            - '../src/EventDispatcher/Event'
            - '../src/Exception'
            - '../src/HttpClient/Model/'
            - '../src/Messenger/Message/'
            - '../src/Workflow/Definition/'
            - '../src/Kernel.php'

    App\Messenger\Dispatcher\SynchroDispatcher:
        arguments:
            $processors: !tagged_iterator app.messenger.dispatcher.synchro

    Gedmo\Blameable\BlameableListener:
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ], ]

    Gedmo\Timestampable\TimestampableListener:
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
